export const navItems = [
    { name: "About", link: "#about" },
    { name: "Projects", link: "#projects" },
    { name: "Blogs" , link: "#blogs"},
    { name: "Experience", link: "#experience" },
    { name: "Contact", link: "#contact" },

  ];
  
  export const projects = [
    {
      id: 1,
      title: "Spring Boot Microservices E-Commerce Project",
      des: "This project is a microservices-based e-commerce system built with Spring Boot and deployed on Kubernetes. The application uses JWT-based security, ensuring secure communication between microservices.",
      img: "/Spring/prj.png",
      secondIcon: "/Spring/Architecture.png",
      iconLists: ["/java.svg","/kafka.svg","/postgres.svg","/mongodb.svg","/docker-svgrepo-com.svg","/kubernetes.svg"],
      visibility: true,
      link: "https://github.com/benabbouosama/Spring-boot-microservices-E-commerce-project",
    },
    {
      id: 2,
      title: "Real-Time Vehicle Tracking System",
      des: "Implementation of a Real-Time Vehicle Tracking System using Kafka, ZooKeeper, Spark, Google Cloud Platform (GCS), BigQuery, Mage, Terraform, dbt, Docker, and Looker Studio. Follow this guide to set up and run the project to monitor and analyze vehicle data in real-time.",
      img: "/real-time/ar.png",
      secondIcon: "/real-time/Architecture.png",
      iconLists: ["/google_cloud-icon.svg","/kafka.svg", "/apache_zookeeper-icon.svg", "/apache-spark-5.svg", "/terraform-svgrepo-com.svg", "/dbt-seeklogo.svg" , "/docker-svgrepo-com.svg"],
      link: "https://github.com/benabbouosama/Real-Time-Vehicle-Tracking-System",
      visibility: true,
    },
    {
      id: 3,
      title: "Forecasting Wikipedia Page Views: An Exploration of Web Traffic Prediction Strategies",
      des: "Constructing a forecasting model for predicting future traffic on Wikipedia pages where we try to explore two different approaches for prediction.",
      img: "/ML/ar.png",
      secondIcon: "/ML/Architecture.png",
      iconLists: ["/Keras.svg", "/tensorflow-icon.svg", "/scikit-learn.svg"],
      link: "https://github.com/benabbouosama/Forecasting-Wikipedia-Page-Views",
      visibility: true,
    },
    {
      id: 4,
      title: "BERT-based Text Classification REST API",
      des: "This project is a FastAPI-based RESTful API for text classification using a fine-tuned BERT model and Cassandra database integration.",
      img: "/Bert-Classification/ar.png",
      secondIcon: "/Bert-Classification/BERT_prj.png", 
      iconLists: ["/fastapi-1.svg", "/apache_cassandra-icon.svg", "/pytorch-icon.svg", "/scikit-learn.svg", "/docker-svgrepo-com.svg"],
      link: "https://github.com/benabbouosama/BERT-based-Text-Classification-REST-API",
      visibility: true,
    },
  ];

  export const blogs = [
    {
      id: 1,
      title: "Implementation of GPT from scratch",
      summary: "Implementation of GPT from scratch",
      content: `Implementing self-attention mechanisms, multi-head attention, and exploring the intricacies of transformer architecture.`,
      date: "Jul 19, 2024",
      link: "https://medium.com/@benabbou.osama/implementation-of-gpt-from-scratch-797c6940c9a8",
      
    },
    {
      id: 2,
      title: "Understanding Transformer Architectures",
      summary: "A comprehensive explanation of the transformer architecture behind BERT and GPT models.",
      content: `Transformers are the backbone of modern NLP models like BERT, GPT, and T5. This article explains the core concepts of transformers, including self-attention mechanisms, encoder-decoder architecture, and how transformers outperform RNNs and LSTMs in NLP tasks.`,
      date: "Soon",
    }, 
    {
      id: 3,
      title: "Environmental Monitoring System",
      summary: "---",
      content: `Simulation of an IoT-based system that monitors temperature, humidity, and pressure across multiple locations. The data generated by the simulated sensors is stored in an InfluxDB database, which can then be visualized using InfluxDB’s built-in Data Explorer or any other data visualization tool that can connect to InfluxDB.`,
      date: "Jan 9, 2024",
      visibility: true,
      link: "https://medium.com/@benabbou.osama/simple-environmental-monitoring-system-using-influxdb-python-simulation-eba0d2e53142",
    },
    
  ];
  
  
  

  
export const socialMedia = [
  {
    id: 1,
    img: "/git.svg",
    link: "https://github.com/benabbouosama",
    name: "GitHub", 
  },
  {
    id: 2,
    img: "/twit.svg",
    link: "https://medium.com/@benabbou.osama",
    name: "Medium", 
  },
  {
    id: 3,
    img: "/link.svg",
    link: "https://www.linkedin.com/in/oussama-benabbou-3a54531b9/",
    name: "LinkedIn", 
  },
];